name: Full-Stack Application CI/CD Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight (00:00 UTC)

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v4
      
      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install the dependencies for backend.
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      # Install the dependencies for frontend.
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      # Run the tests for backend.
      - name: Run backend tests
        run: |
          cd backend
          npm test

      # Run the tests for frontend.
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      # Run the linter for backend.
      - name: Run backend linter
        run: |
          cd backend
          npm run lint

      # Run the linter for frontend.
      - name: Run frontend linter
        run: |
          cd frontend
          npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."